name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches: '*'

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Conda environment from environment.yml
      uses: mamba-org/provision-with-micromamba@main

    - name: Build the extension
      run: |
        python -m pip install .

        jupyter labextension list 2>&1 | grep -ie "jupyterlab-filesystem-access.*OK"
        python -m jupyterlab.browser_check

        check-manifest -v

        python -m build --sdist
        cp dist/*.tar.gz jupyterlab-filesystem-access.tar.gz
        pip uninstall -y "jupyterlab_filesystem_access" jupyterlab
        rm -rf jupyterlab-filesystem-access

    - uses: actions/upload-artifact@v2
      with:
        name: jupyterlab-filesystem-access-sdist
        path: jupyterlab-filesystem-access.tar.gz

  test_isolated:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Conda environment from environment.yml
      uses: mamba-org/provision-with-micromamba@main
    - uses: actions/download-artifact@v2
      with:
        name: jupyterlab-filesystem-access-sdist
    - name: Install and Test
      run: |
        pip install jupyterlab-filesystem-access.tar.gz
        jupyter labextension list 2>&1 | grep -ie "jupyterlab-filesystem-access.*OK"
        python -m jupyterlab.browser_check --no-chrome-test
