name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches: '*'

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Conda environment from environment.yml
      uses: mamba-org/provision-with-micromamba@main

    - name: Lint
      run: |
        jlpm
        jlpm lint:check